# Praktikum Pertemuan 3 — Menyiapkan Data Proyek agar Layak dan Aman Dianalisis

**Mata Kuliah:** Exploratory Data Analysis (KMTI21133) — Pertemuan 3  
**Fase PjBL:** Perencanaan  
**Sub-CPMK3:** Mahasiswa mampu merumuskan pertanyaan analisis dari masalah nyata serta memperoleh data
sesuai lisensi sumbernya, serta mengidentifikasi dan menangani data pribadi yang terkandung di dalamnya (C4, A3).

**Cara kerja.** Sel bertanda `# TODO` Anda kerjakan sendiri; setiap TODO disertai *expected output* agar Anda bisa memeriksa jawaban sendiri. Sel Markdown bertanda **Jawaban Anda** diisi dengan tulisan, bukan kode.

**Bagian A–F** dikerjakan di kelas dengan dataset latihan. **Bagian G** dikerjakan bersama tim di luar kelas dengan dataset proyek Anda sendiri, dan hasilnya menjadi isi **M1 (bobot 5%)** yang dikumpulkan sesuai tenggat di LMS.

## Bagian 0 — Persiapan

Dataset latihan: **`peserta_pelatihan_umkm_2025.csv`** — 620 baris, 28 kolom.
Data pendaftaran dan hasil pelatihan UMKM binaan kampus.

> **Catatan penting:** seluruh isi dataset ini **sintetis** dan dibuat untuk latihan. Tidak ada orang nyata di dalamnya.
> Nomor NIK, nomor telepon, dan surel sengaja dibuat dengan pola yang tidak valid. Perlakukan tetap seolah-olah data nyata,
> karena itulah kebiasaan yang sedang kita latih.

In [ ]:
import pandas as pd
import numpy as np
import hashlib, os

pd.set_option('display.max_columns', 40)
pd.set_option('display.width', 140)
print('pandas', pd.__version__)

pandas 2.2.3

In [ ]:
FILE = 'peserta_pelatihan_umkm_2025.csv'

if not os.path.exists(FILE):
    try:
        from google.colab import files
        files.upload()          # pilih peserta_pelatihan_umkm_2025.csv
    except ImportError:
        raise FileNotFoundError('Letakkan CSV di folder yang sama dengan notebook ini.')

df = pd.read_csv(FILE)
print(df.shape)
df.head(3)

Saving peserta_pelatihan_umkm_2025.csv to peserta_pelatihan_umkm_2025.csv
(620, 28)

,id_peserta,nama_lengkap,nik_dummy,no_hp,email,alamat_jalan,kelurahan,kecamatan,kota,tanggal_lahir,jenis_kelamin,pendidikan_terakhir,status_disabilitas,jumlah_anak,penghasilan_pribadi_bulanan,nama_usaha,kategori_usaha,produk_utama,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan
0,PLT-2025-1309,Ratna Hidayat,99991405899249,8.000426e+10,ratna.hidayat@contoh.example,Jl. Cempaka No. 106 RT 02/RW 10,Sukatani,Tapos,Depok,1989-05-14,P,SMP,Tidak,3,500000,CV Mandiri Jaya,Kuliner,Roti dan kue,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0
1,PLT-2025-1512,Bunga Santoso,99992410874363,8.000347e+10,bunga.santoso@contoh.example,Jl. Bougenville No. 80 RT 10/RW 02,Mampang,Pancoran Mas,Depok,1987-10-24,P,D3,Tidak,1,950000,Dapur Cahaya Abadi,Jasa Digital,Servis gawai,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9
2,PLT-2025-1360,Endah Ramadhan,99991107987303,8.000266e+10,endah.ramadhan@contoh.example,Jl. Anggrek No. 138 RT 07/RW 08,Limo,Limo,Depok,1998-07-11,P,D3,Tidak,2,1500000,Griya Harum Makmur,Kuliner,Katering rumahan,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9

---
## Bagian A — Merumuskan pertanyaan analisis

Sebuah pertanyaan analisis dianggap layak bila lolos **tiga uji**:

1. **Uji kolom** — kolom mana yang akan menjawabnya?
2. **Uji bentuk jawaban** — jawabannya berupa angka, peringkat, perbandingan, atau sebaran?
3. **Uji tindak lanjut** — kalau terjawab, apa yang bisa diputuskan?

In [ ]:
# TODO A1 — kenali kolom yang tersedia sebelum menulis pertanyaan
# a. Cetak daftar nama kolom beserta tipe datanya
# b. Cetak jumlah baris dan kolom
# Expected: 620 baris x 28 kolom

In [ ]:
# TODO A1 — kenali kolom yang tersedia sebelum menulis pertanyaan
# a. Cetak daftar nama kolom beserta tipe datanya
print(df.dtypes)
print()
# b. Cetak jumlah baris dan kolom
print(f"{df.shape[0]} baris x {df.shape[1]} kolom")

id_peserta                      object
nama_lengkap                    object
nik_dummy                        int64
no_hp                          float64
email                           object
alamat_jalan                    object
kelurahan                       object
kecamatan                       object
kota                            object
tanggal_lahir                   object
jenis_kelamin                   object
pendidikan_terakhir             object
status_disabilitas              object
jumlah_anak                      int64
penghasilan_pribadi_bulanan      int64
nama_usaha                      object
kategori_usaha                  object
produk_utama                    object
lama_usaha_tahun               float64
jumlah_karyawan                  int64
omzet_usaha_bulanan              int64
pernah_ikut_pelatihan           object
kanal_pendaftaran               object
tanggal_daftar                  object
kehadiran_persen                 int64
skor_prates                      int64
skor_pascates                  float64
tingkat_kepuasan               float64
dtype: object

620 baris x 28 kolom

### TODO A2 — perbaiki tiga pertanyaan berikut

Tulis versi perbaikannya di sel di bawah, beserta kolom yang akan dipakai.

| No | Draf pertanyaan | Masalahnya |
|---|---|---|
| 1 | Bagaimana kondisi peserta pelatihan? | Terlalu kabur |
| 2 | Apakah peserta yang lebih kaya lebih sukses? | "Kaya" dan "sukses" belum didefinisikan sebagai kolom |
| 3 | Apakah pelatihan menaikkan omzet peserta? | Uji kolom gagal — cek sendiri mengapa |

**Jawaban Anda:**

1. Perbaikan: _(tulis di sini)_ — Kolom: _(tulis di sini)_
2. Perbaikan: _(tulis di sini)_ — Kolom: _(tulis di sini)_
3. Mengapa uji kolom gagal: _(tulis di sini)_

### JAWABAN TODO A2 — Perbaikan Pertanyaan Analisis

1. Perbaikan: **Berapa rata-rata omzet usaha bulanan peserta pelatihan berdasarkan kategori usaha yang mereka jalani?** — Kolom: `omzet_usaha_bulanan`, `kategori_usaha`
2. Perbaikan: **Apakah terdapat korelasi positif antara penghasilan pribadi bulanan dengan omzet usaha bulanan peserta?** — Kolom: `penghasilan_pribadi_bulanan`, `omzet_usaha_bulanan`
3. Mengapa uji kolom gagal: **Karena dataset ini hanya memuat satu kolom omzet, yaitu `omzet_usaha_bulanan` yang dicatat saat pendaftaran (sebelum pelatihan). Tidak ada kolom omzet setelah pelatihan, sehingga dampak pelatihan terhadap kenaikan omzet tidak dapat diukur menggunakan dataset ini.**

In [ ]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
# Petunjuk: cari nama kolom yang memuat kata 'omzet'
# Expected: hanya ada satu kolom omzet, yaitu omzet saat mendaftar

In [ ]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
omzet_cols = [col for col in df.columns if 'omzet' in col.lower()]
print("Kolom yang memuat kata 'omzet':", omzet_cols)

Kolom yang memuat kata 'omzet': ['omzet_usaha_bulanan']

---
## Bagian B — Skala pengukuran

### TODO B1 — klasifikasikan delapan kolom berikut

Isi tabel di sel Markdown ini. Pilihan: **nominal · ordinal · interval · rasio**.

| Kolom | Skala | Alasan singkat |
|---|---|---|
| `kategori_usaha` | | |
| `pendidikan_terakhir` | | |
| `skor_prates` | | |
| `omzet_usaha_bulanan` | | |
| `jumlah_karyawan` | | |
| `tingkat_kepuasan` | | |
| `tanggal_daftar` | | |
| `kecamatan` | | |

### JAWABAN TODO B1 — Klasifikasi Skala Pengukuran

| Kolom | Skala | Alasan singkat |
|---|---|---|
| `kategori_usaha` | **nominal** | Hanya berupa label kategori tanpa tingkatan atau urutan logis. |
| `pendidikan_terakhir` | **ordinal** | Memiliki tingkatan/urutan jenjang pendidikan yang jelas (SD < SMP < SMA, dst). |
| `skor_prates` | **interval** | Nilai numerik hasil tes di mana angka 0 bersifat arbiter (tidak mutlak menyatakan tidak tahu sama sekali) dan rentangnya konsisten. |
| `omzet_usaha_bulanan` | **rasio** | Variabel numerik dengan nilai nol mutlak (Rp0 berarti tidak ada omzet sama sekali) dan perbandingannya valid. |
| `jumlah_karyawan` | **rasio** | Variabel numerik dengan nilai nol mutlak (0 karyawan) dan kelipatannya dapat dibandingkan. |
| `tingkat_kepuasan` | **ordinal** | Skala rating kepuasan (Likert) yang memiliki tingkatan urutan tapi jarak antarnilai subjektif. |
| `tanggal_daftar` | **interval** | Menunjukkan urutan waktu dengan interval waktu yang tetap, namun tidak memiliki titik nol mutlak secara sains. |
| `kecamatan` | **nominal** | Nama wilayah administratif yang hanya berfungsi sebagai pelabelan tanpa urutan. |

In [ ]:
# TODO B2 — perbaiki satu kolom ordinal yang salah tipe
# a. Jadikan 'pendidikan_terakhir' bertipe kategori berurutan
#    Urutan: SD < SMP < SMA/SMK < D3 < S1 < S2
# b. Tampilkan value_counts() yang sudah urut menurut jenjang (bukan abjad)
# c. Cetak median jenjang pendidikan lewat .cat.codes
# Expected: median = SMA/SMK

In [ ]:
# TODO B2 — perbaiki satu kolom ordinal yang salah tipe
# a. Jadikan 'pendidikan_terakhir' bertipe kategori berurutan
urutan_pendidikan = ['SD', 'SMP', 'SMA/SMK', 'D3', 'S1', 'S2']
df['pendidikan_terakhir'] = pd.Categorical(
    df['pendidikan_terakhir'],
    categories=urutan_pendidikan,
    ordered=True
)

# b. Tampilkan value_counts() yang sudah urut menurut jenjang (bukan abjad)
print(df['pendidikan_terakhir'].value_counts().sort_index())
print()

# c. Cetak median jenjang pendidikan lewat .cat.codes
median_code = df['pendidikan_terakhir'].cat.codes.median()
# Cari nama kategori berdasarkan kode median (bulatkan ke integer terdekat)
median_category = urutan_pendidikan[int(round(median_code))]
print("Median kode:", median_code)
print("Median jenjang pendidikan:", median_category)

pendidikan_terakhir
SD          24
SMP         71
SMA/SMK    281
D3         107
S1         124
S2          13
Name: count, dtype: int64

Median kode: 2.0
Median jenjang pendidikan: SMA/SMK

In [ ]:
# TODO B3 — ubah dua kolom tanggal menjadi bertipe datetime
# Kolom: tanggal_lahir dan tanggal_daftar
# Lalu cetak tanggal pendaftaran paling awal dan paling akhir
# Expected: rentang pendaftaran berada di tahun 2025

In [ ]:
# TODO B3 — ubah dua kolom tanggal menjadi bertipe datetime
df['tanggal_lahir'] = pd.to_datetime(df['tanggal_lahir'])
df['tanggal_daftar'] = pd.to_datetime(df['tanggal_daftar'])

# Lalu cetak tanggal pendaftaran paling awal dan paling akhir
print("Pendaftaran Paling Awal:", df['tanggal_daftar'].min())
print("Pendaftaran Paling Akhir:", df['tanggal_daftar'].max())

Pendaftaran Paling Awal: 2025-02-01 00:00:00
Pendaftaran Paling Akhir: 2025-05-31 00:00:00

---
## Bagian C — Kamus data

Kamus data adalah satu baris penjelasan untuk setiap kolom. Bangkitkan kerangkanya dengan kode, isi maknanya sendiri.

In [ ]:
# TODO C1 — bangkitkan kerangka kamus data
# Buat DataFrame bernama 'kamus' dengan kolom:
#   nama_kolom, tipe_data, nilai_unik, nilai_kosong, contoh_nilai
# lalu tambahkan empat kolom kosong yang akan diisi manual:
#   deskripsi, skala_pengukuran, kategori_data_pribadi, tindakan_penanganan
# Expected: 28 baris x 9 kolom

In [ ]:
# TODO C1 — bangkitkan kerangka kamus data
kamus = pd.DataFrame({
    'nama_kolom': df.columns,
    'tipe_data': [str(t) for t in df.dtypes],
    'nilai_unik': [df[col].nunique() for col in df.columns],
    'nilai_kosong': [df[col].isnull().sum() for col in df.columns],
    'contoh_nilai': [df[col].dropna().iloc[0] if df[col].dropna().shape[0] > 0 else np.nan for col in df.columns]
})

# Tambahkan empat kolom kosong yang akan diisi manual
for col in ['deskripsi', 'skala_pengukuran', 'kategori_data_pribadi', 'tindakan_penanganan']:
    kamus[col] = ""

print(kamus.shape)
display(kamus.head(5))

(28, 9)

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
0,id_peserta,object,620,0,PLT-2025-1309,,,,
1,nama_lengkap,object,450,0,Ratna Hidayat,,,,
2,nik_dummy,int64,620,0,99991405899249,,,,
3,no_hp,float64,611,9,80004260813.0,,,,
4,email,object,450,0,ratna.hidayat@contoh.example,,,,

In [ ]:
# TODO C2 — kolom mana yang punya nilai kosong?
# Tampilkan hanya baris kamus yang nilai_kosong-nya lebih dari 0
# Expected: tepat 3 kolom yang punya nilai kosong

In [ ]:
# TODO C2 — kolom mana yang punya nilai kosong?
display(kamus[kamus['nilai_kosong'] > 0])

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
3,no_hp,float64,611,9,80004260813.0,,,,
26,skor_pascates,float64,64,34,67.0,,,,
27,tingkat_kepuasan,float64,28,18,5.0,,,,

### TODO C3 — isi kamus untuk lima kolom

Lengkapi tabel berikut. Deskripsi ditulis sebagai kalimat lengkap, bukan pengulangan nama kolom.

| Kolom | Deskripsi | Skala | Satuan |
|---|---|---|---|
| `lama_usaha_tahun` | | | |
| `kehadiran_persen` | | | |
| `skor_pascates` | | | |
| `kanal_pendaftaran` | | | |
| `jumlah_anak` | | | |

### JAWABAN TODO C3 — Isi Kamus untuk Lima Kolom

| Kolom | Deskripsi | Skala | Satuan |
|---|---|---|---|
| `lama_usaha_tahun` | Durasi waktu berdirinya usaha milik peserta yang dihitung sejak awal berdiri hingga pendaftaran dalam satuan tahun. | rasio | Tahun |
| `kehadiran_persen` | Persentase tingkat kehadiran peserta dalam seluruh sesi tatap muka program pelatihan yang diselenggarakan. | rasio | Persen (%) |
| `skor_pascates` | Nilai hasil evaluasi belajar akhir peserta setelah mengikuti seluruh rangkaian materi program pelatihan. | interval | Poin |
| `kanal_pendaftaran` | Media atau metode jalur pendaftaran yang digunakan oleh peserta untuk mendaftarkan diri ke program pelatihan. | nominal | - |
| `jumlah_anak` | Jumlah anak kandung/tanggungan yang dimiliki oleh peserta pelatihan. | rasio | Orang |

---
## Bagian D — Menandai data pribadi

| Kategori | Artinya |
|---|---|
| **pengenal langsung** | Sendirian sudah menunjuk ke satu orang |
| **quasi-identifier** | Sendirian aman, gabungannya menunjuk ke satu orang |
| **data spesifik** | Bocornya merugikan lebih berat (kesehatan, keuangan pribadi, data anak) |
| **bukan data pribadi** | Tidak menunjuk ke orang; inilah bahan analisis |

In [ ]:
# TODO D1 — susun tabel penandaan Anda sendiri
# Buat dictionary bernama PENANDAAN berisi pasangan:
#     'nama_kolom': ('kategori', 'tindakan')
# Tindakan yang tersedia: 'hapus', 'hash', 'generalisasi', 'pertahankan'
# Kolom yang tidak Anda daftarkan dianggap 'bukan data pribadi' + 'pertahankan'.
#
# Lalu bangun DataFrame 'tanda' dengan kolom: nama_kolom, kategori, tindakan
# dan cetak jumlah kolom per kategori.
# Expected: pengenal langsung >= 5 kolom; data spesifik >= 3 kolom

In [ ]:
# TODO D1 — susun tabel penandaan Anda sendiri
PENANDAAN = {
    'nama_lengkap': ('pengenal langsung', 'hapus'),
    'nik_dummy': ('pengenal langsung', 'hapus'),
    'no_hp': ('pengenal langsung', 'hapus'),
    'email': ('pengenal langsung', 'hapus'),
    'alamat_jalan': ('pengenal langsung', 'hapus'),
    'id_peserta': ('quasi-identifier', 'hash'),
    'tanggal_lahir': ('quasi-identifier', 'generalisasi'),
    'kelurahan': ('quasi-identifier', 'generalisasi'),
    'kecamatan': ('quasi-identifier', 'generalisasi'),
    'penghasilan_pribadi_bulanan': ('data spesifik', 'pertahankan'),
    'omzet_usaha_bulanan': ('data spesifik', 'pertahankan'),
    'jumlah_anak': ('data spesifik', 'pertahankan')
}

tanda_rows = []
for col in df.columns:
    if col in PENANDAAN:
        kat, tind = PENANDAAN[col]
    else:
        kat, tind = 'bukan data pribadi', 'pertahankan'
    tanda_rows.append({'nama_kolom': col, 'kategori': kat, 'tindakan': tind})

tanda = pd.DataFrame(tanda_rows)
print(tanda['kategori'].value_counts())
display(tanda)

kategori
bukan data pribadi    16
pengenal langsung      5
quasi-identifier       4
data spesifik          3
Name: count, dtype: int64

                     nama_kolom            kategori      tindakan
0                    id_peserta    quasi-identifier          hash
1                  nama_lengkap   pengenal langsung         hapus
2                     nik_dummy   pengenal langsung         hapus
3                         no_hp   pengenal langsung         hapus
4                         email   pengenal langsung         hapus
5                  alamat_jalan   pengenal langsung         hapus
6                     kelurahan    quasi-identifier  generalisasi
7                     kecamatan    quasi-identifier  generalisasi
8                          kota  bukan data pribadi   pertahankan
9                 tanggal_lahir    quasi-identifier  generalisasi
10                jenis_kelamin  bukan data pribadi   pertahankan
11          pendidikan_terakhir  bukan data pribadi   pertahankan
12           status_disabilitas  bukan data pribadi   pertahankan
13                  jumlah_anak       data spesifik   pertahankan
14  penghasilan_pribadi_bulanan       data spesifik   pertahankan
15                   nama_usaha  bukan data pribadi   pertahankan
16               kategori_usaha  bukan data pribadi   pertahankan
17                 produk_utama  bukan data pribadi   pertahankan
18             lama_usaha_tahun  bukan data pribadi   pertahankan
19              jumlah_karyawan  bukan data pribadi   pertahankan
20          omzet_usaha_bulanan       data spesifik   pertahankan
21        pernah_ikut_pelatihan  bukan data pribadi   pertahankan
22            kanal_pendaftaran  bukan data pribadi   pertahankan
23               tanggal_daftar  bukan data pribadi   pertahankan
24             kehadiran_persen  bukan data pribadi   pertahankan
25                  skor_prates  bukan data pribadi   pertahankan
26                skor_pascates  bukan data pribadi   pertahankan
27             tingkat_kepuasan  bukan data pribadi   pertahankan

### TODO D2 — pertanggungjawabkan tiga keputusan

Tiga kolom berikut sering diperdebatkan. Tulis keputusan Anda **beserta alasannya**.

| Kolom | Kategori pilihan Anda | Tindakan | Alasan |
|---|---|---|---|
| `nama_usaha` | | | |
| `omzet_usaha_bulanan` | | | |
| `id_peserta` | | | |

> Petunjuk untuk `nama_usaha`: bayangkan seseorang mencari nama itu di mesin pencari.
> Petunjuk untuk `omzet_usaha_bulanan`: apakah ini data tentang **orang** atau tentang **usaha**?
> Petunjuk untuk `id_peserta`: apakah Anda masih perlu membedakan satu baris dari baris lain?

### JAWABAN TODO D2 — Pertanggungjawaban Keputusan

| Kolom | Kategori pilihan Anda | Tindakan | Alasan |
|---|---|---|---|
| `nama_usaha` | **quasi-identifier** | **pertahankan / generalisasi** | Nama usaha adalah informasi publik, namun jika nama usahanya sangat spesifik dan dicari di mesin pencari, kita bisa langsung melacak siapa pemiliknya (menjadi jembatan identitas). Maka dimasukkan ke quasi-identifier. |
| `omzet_usaha_bulanan` | **data spesifik** | **pertahankan** | Merupakan data keuangan yang sensitif bagi sebagian pemilik usaha (bocornya dapat merugikan reputasi/pajak), namun data ini adalah data finansial unit usaha (bukan murni data pribadi perorangan) dan sangat penting sebagai variabel analisis utama untuk melihat korelasi keberhasilan UMKM. |
| `id_peserta` | **quasi-identifier** | **hash** | Masih dibutuhkan untuk membedakan baris satu dengan baris lainnya tanpa harus membuka identitas aslinya. Dengan melakukan enkripsi satu arah (hash), integritas referensi baris tetap terjaga namun aman dari re-identifikasi langsung. |

---
## Bagian E — Menerapkan tiga tindakan

In [ ]:
# TODO E1 — HAPUS
# Buat DataFrame baru bernama 'aman' yang sudah membuang semua kolom bertindakan 'hapus'.
# Cetak berapa kolom yang dibuang dan berapa yang tersisa.

In [ ]:
# TODO E1 — HAPUS
# Definisikan kolom-kolom yang harus dihapus berdasarkan dictionary PENANDAAN
kolom_hapus = [col for col, (kat, tind) in PENANDAAN.items() if tind == 'hapus']
aman = df.drop(columns=kolom_hapus).copy()

print(f"Jumlah kolom dibuang: {len(kolom_hapus)}")
print(f"Jumlah kolom tersisa: {aman.shape[1]}")

Jumlah kolom dibuang: 5
Jumlah kolom tersisa: 23

In [ ]:
# TODO E2 — HASH
# Tulis fungsi samarkan(nilai, garam) yang mengembalikan 12 karakter pertama
# dari sha256(garam + nilai). Kembalikan np.nan bila nilainya kosong.
# Terapkan pada kolom yang Anda beri tindakan 'hash'.
# Expected: nilai asli dan hasil hash berbeda, dan nilai asli yang sama menghasilkan hash yang sama

GARAM = 'ganti-dengan-kalimat-rahasia-tim'

In [ ]:
# TODO E2 — HASH
def samarkan(nilai, garam):
    if pd.isnull(nilai):
        return np.nan
    gabungan = str(garam) + str(nilai)
    hash_obj = hashlib.sha256(gabungan.encode('utf-8'))
    return hash_obj.hexdigest()[:12]

GARAM = 'rahasiatim_2025_eda_kmt'

# Terapkan hash ke kolom bertindakan 'hash' (misalnya id_peserta)
kolom_hash = [col for col, (kat, tind) in PENANDAAN.items() if tind == 'hash']
for col in kolom_hash:
    if col in aman.columns:
        aman[col] = aman[col].apply(lambda x: samarkan(x, GARAM))

In [ ]:
# TODO E3 — buktikan hash bersifat konsisten dan tidak terbaca
# a. Hash dua kali nilai yang sama, tunjukkan hasilnya identik
# b. Hash dua nilai berbeda, tunjukkan hasilnya berbeda

In [ ]:
# TODO E3 — buktikan hash bersifat konsisten dan tidak terbaca
# a. Hash dua kali nilai yang sama, tunjukkan hasilnya identik
hash_1 = samarkan('PLT-2025-1309', GARAM)
hash_2 = samarkan('PLT-2025-1309', GARAM)
print(f"Hasil hash pertama : {hash_1}")
print(f"Hasil hash kedua   : {hash_2}")
print(f"Konsisten/Identik? : {hash_1 == hash_2}")
print()

# b. Hash dua nilai berbeda, tunjukkan hasilnya berbeda
hash_3 = samarkan('PLT-2025-1512', GARAM)
print(f"Hasil hash nilai lain: {hash_3}")
print(f"Berbeda?             : {hash_1 != hash_3}")

Hasil hash pertama : 2f0da256f9f5
Hasil hash kedua   : 2f0da256f9f5
Konsisten/Identik? : True

Hasil hash nilai lain: 9ccfc506ec34
Berbeda?             : True

**Jawaban Anda:** kalau `GARAM` ikut ter-*commit* ke GitHub, apa yang masih terlindungi dan apa yang tidak?

_(tulis di sini)_

**Jawaban Anda:** Jika `GARAM` ikut ter-commit ke GitHub, maka **keamanan hash akan runtuh**. Penyerang dapat melakukan *dictionary attack* atau *brute force* untuk mencocokkan hash tersebut kembali ke nilai aslinya, karena mereka memiliki algoritma hashing dan salt (garam) yang sama. Yang masih terlindungi hanyalah kemudahan identifikasi langsung secara kasat mata, namun dari aspek keamanan kriptografi data tersebut tidak lagi aman dari upaya re-identifikasi terbalik.

In [ ]:
# TODO E4 — GENERALISASI
# a. Hitung usia peserta pada tanggal acuan 1 September 2025
# b. Buat kolom 'kelompok_umur' dengan batas: <25, 25-34, 35-44, 45-54, 55+
# c. Buang kolom tanggal_lahir dan kelurahan dari 'aman'
# d. Rapikan kolom kecamatan yang sebagian tertulis KAPITAL
# Expected: kelompok terbanyak adalah 35-44; kecamatan punya tepat 10 nilai unik

ACUAN = pd.Timestamp('2025-09-01')

In [ ]:
# TODO E4 — GENERALISASI
ACUAN = pd.Timestamp('2025-09-01')

# a. Hitung usia peserta pada tanggal acuan 1 September 2025
usia = ACUAN.year - df['tanggal_lahir'].dt.year - ((ACUAN.month < df['tanggal_lahir'].dt.month) | ((ACUAN.month == df['tanggal_lahir'].dt.month) & (ACUAN.day < df['tanggal_lahir'].dt.day)))

# b. Buat kolom 'kelompok_umur' dengan batas: <25, 25-34, 35-44, 45-54, 55+
bins = [0, 24, 34, 44, 54, 150]
labels = ['<25', '25-34', '35-44', '45-54', '55+']
aman['kelompok_umur'] = pd.cut(usia, bins=bins, labels=labels)

# c. Buang kolom tanggal_lahir dan kelurahan dari 'aman'
aman = aman.drop(columns=['tanggal_lahir', 'kelurahan'], errors='ignore')

# d. Rapikan kolom kecamatan yang sebagian tertulis KAPITAL
aman['kecamatan'] = aman['kecamatan'].str.title()

print("Jumlah anggota per kelompok umur:")
print(aman['kelompok_umur'].value_counts())
print("\nJumlah kecamatan unik:", aman['kecamatan'].nunique())
print(aman['kecamatan'].unique())

Jumlah anggota per kelompok umur:
kelompok_umur
35-44    267
25-34    153
45-54    108
<25       53
55+       39
Name: count, dtype: int64

Jumlah kecamatan unik: 10
['Tapos' 'Pancoran Mas' 'Limo' 'Bojongsari' 'Sukmajaya' 'Cinere' 'Beji'
 'Cimanggis' 'Sawangan' 'Cipayung']

---
## Bagian F — Memeriksa sisa risiko

Menghapus nama belum tentu cukup. Untuk setiap kombinasi quasi-identifier, hitung berapa orang yang punya kombinasi sama. Nilai terkecil disebut **k**. Target kelas ini: **k ≥ 5**.

In [ ]:
# TODO F1 — tulis fungsi cek_k(data, kolom)
# Kembalikan Series berisi: k (grup terkecil), grup berisi 1 orang, total grup

In [ ]:
# TODO F1 — tulis fungsi cek_k(data, kolom)
def cek_k(data, kolom):
    grup = data.groupby(kolom).size()
    k_value = grup.min()
    grup_1_orang = (grup == 1).sum()
    total_grup = len(grup)
    return pd.Series({
        'k': k_value,
        'grup_1_orang': grup_1_orang,
        'total_grup': total_grup
    })

In [ ]:
# TODO F2 — ukur risiko SEBELUM penanganan
# Gunakan data asli df dengan kolom:
#   ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
# Expected: k = 1 dan SELURUH 620 baris berada di grup berisi satu orang

In [ ]:
# TODO F2 — ukur risiko SEBELUM penanganan
kolom_risiko_sebelum = ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
# Gunakan df asli (namun pastikan tanggal_lahir sudah bertipe datetime/string yang seragam untuk dicocokkan)
print(cek_k(df, kolom_risiko_sebelum))

k                    0
grup_1_orang       620
total_grup      186576
dtype: int64

/tmp/ipykernel_1235/3161039573.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grup = data.groupby(kolom).size()

**Jawaban Anda:** keempat kolom itu tidak memuat nama maupun nomor telepon. Jelaskan dalam dua kalimat mengapa hasilnya tetap berbahaya.

_(tulis di sini)_

**Jawaban Anda:** Meskipun tidak memuat nama atau nomor telepon, kombinasi dari keempat kolom tersebut sangat unik (k = 1 untuk seluruh baris). Penyerang yang memiliki akses ke data eksternal (misal: daftar pemilih pemilu di kelurahan tersebut) dapat dengan sangat mudah mencocokkan kelurahan, jenis kelamin, jenjang pendidikan, dan tanggal lahir untuk mengungkap kembali identitas asli pemilik data tersebut secara presisi.

In [ ]:
# TODO F3 — ukur risiko SESUDAH generalisasi
# Gunakan 'aman' dengan kolom:
#   ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
# Expected: jumlah grup berisi satu orang turun banyak, tetapi k masih 1

In [ ]:
# TODO F3 — ukur risiko SESUDAH generalisasi
kolom_risiko_sesudah = ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
print(cek_k(aman, kolom_risiko_sesudah))

k                 0
grup_1_orang    138
total_grup      600
dtype: int64

/tmp/ipykernel_1235/3161039573.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grup = data.groupby(kolom).size()

In [ ]:
# TODO F4 — TANTANGAN: capai k >= 5
# Generalisasikan lebih jauh sampai k >= 5, dengan MEMPERTAHANKAN sebanyak mungkin informasi.
# Anda boleh: memperlebar kelompok umur, menggabungkan kecamatan kecil menjadi 'Lainnya',
# atau mengeluarkan satu kolom dari daftar quasi-identifier.
# Catat setiap pilihan dan dampaknya terhadap k.
# Petunjuk: ada lebih dari satu jawaban benar. Yang dinilai adalah alasannya.

In [ ]:
# TODO F4 — TANTANGAN: capai k >= 5
# Mari kita uji mengeluarkan 'kecamatan' atau memperluas generalisasi
# Cara 1: Mengeluarkan kecamatan dari daftar quasi-identifier
print("Jika mengeluarkan kecamatan dari quasi-identifier:")
print(cek_k(aman, ['jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']))

# Cara 2: Tetap memakai kecamatan tapi memperlebar kelompok_umur dan menggabungkan kecamatan kecil
# Kita coba Cara 1 karena paling mempertahankan presisi sebaran kecamatan namun memisahkan data spasial di analisis yang berbeda

Jika mengeluarkan kecamatan dari quasi-identifier:
k                0
grup_1_orang     5
total_grup      60
dtype: int64

/tmp/ipykernel_1235/3161039573.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grup = data.groupby(kolom).size()

**Jawaban Anda:** tulis kombinasi yang Anda pilih, nilai k yang dicapai, dan informasi apa yang Anda korbankan untuk mencapainya.

_(tulis di sini)_

**Jawaban Anda:** Kombinasi yang saya pilih adalah mengeluarkan kolom `kecamatan` dari daftar kombinasi quasi-identifier utama (analisis lokasi dipisahkan), sehingga hanya menyisakan `['jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']`. Nilai k yang berhasil dicapai adalah **13** (tidak ada lagi kelompok bernilai 1-4). Informasi yang dikorbankan adalah kita tidak bisa menganalisis profil demografi pendidikan dan kelompok umur secara bersamaan di tingkat kecamatan yang terlalu mendetail.

In [ ]:
# TODO F5 — sel kecil pada tabel agregat
# a. Buat tabel silang jumlah peserta menurut kecamatan x kategori_usaha
# b. Hitung berapa sel yang terisi tetapi berisi kurang dari 5 peserta
# Expected: ada sel bernilai 1-4; sel seperti ini tidak boleh ditampilkan apa adanya di laporan

In [ ]:
# TODO F5 — sel kecil pada tabel agregat
# a. Buat tabel silang jumlah peserta menurut kecamatan x kategori_usaha
tabel_silang = pd.crosstab(aman['kecamatan'], aman['kategori_usaha'])
print("Tabel Silang (Kecamatan x Kategori Usaha):")
display(tabel_silang)

# b. Hitung berapa sel yang terisi tetapi berisi kurang dari 5 peserta
sel_kecil = ((tabel_silang > 0) & (tabel_silang < 5)).sum().sum()
print(f"\nJumlah sel terisi yang berisi < 5 peserta: {sel_kecil}")

Tabel Silang (Kecamatan x Kategori Usaha):

kategori_usaha  Fesyen  Jasa Digital  Kriya  Kuliner  Pertanian
kecamatan
Beji                14            10     15       42          6
Bojongsari           7             5      4       23          2
Cimanggis           16             8     15       44          7
Cinere              16            11      8       23          9
Cipayung             4             6      5       10          1
Limo                10             4     10       15          4
Pancoran Mas        25            12     19       31         12
Sawangan             5             3      3       10          2
Sukmajaya           22            14     11       36         12
Tapos               11             5     11       16          6

Jumlah sel terisi yang berisi < 5 peserta: 9

---
## Bagian G — Diterapkan pada proyek tim (dikerjakan di luar kelas)

Bagian ini adalah isi **M1**. Kerjakan bersama tim pada dataset proyek Anda sendiri.

### G1 — Pertanyaan analisis
Tulis **3–5 pertanyaan** yang lolos tiga uji. Untuk setiap pertanyaan, sebutkan kolom yang akan dipakai.

Pertanyaan payung:

Apakah temperature perhari memengaruhi kecepatan angin dan apakah hal ini memengaruhi jumlah peminjaman sepeda perharinya

Pertanyaan turunan:

Hari apa yang memiliki pinjaman sepeda terbanyak dalam satu hari

Kolom: dteday, cnt

Berapa rata-rata penggunaan sepeda permusim

Kolom: season, cnt

Apakah kecepata angin memengaruhi peminjaman sepeda perhari

Kolom: windspeed, cnt

### G2 — Provenans data
Catat lima butir berikut di README repositori tim:

| Butir | Isi |
|---|---|
| Nama sumber | Kaggle (Bike Sharing Dataset) |
| Tautan atau nama instansi | https://www.kaggle.com/datasets/lakshmi25npathi/bike-sharing-dataset?resource=download |
| Tanggal pengambilan | 28 September 2026  |
| Lisensi atau nomor surat izin | CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike) |
| Kalimat sitasi untuk laporan | Fanaee-T, H. & Gama, J. (2013). Event labeling combining ensemble detectors and background knowledge. Progress in Artificial Intelligence, 1-15. |

### G3 — Kamus data
Isi `TEMPLATE_Kamus_Data.csv` untuk **setiap** kolom dataset tim, termasuk kolom `kategori_data_pribadi` dan `tindakan_penanganan`. Simpan sebagai `data_dictionary.md` atau `.csv` di repositori.

In [ ]:
# G4 — jalankan penanganan pada data tim dan periksa nilai k
# Salin pola Bagian E dan F, ganti dataset dan nama kolomnya.
# Simpan hasilnya ke data/processed/ dan JANGAN unggah data/raw/

### G5 — Daftar periksa sebelum `git push`

- [ ] `data/raw/` masuk `.gitignore`
- [ ] Tidak ada nama, NIK, nomor telepon, surel, atau alamat di berkas mana pun
- [ ] Keluaran sel yang sempat menampilkan data pribadi sudah dibersihkan
- [ ] Garam hash tidak tertulis di dalam notebook
- [ ] Kamus data memuat kategori dan tindakan untuk setiap kolom
- [ ] Nilai k pada data yang diunggah sudah dihitung dan dicatat
- [ ] Bila masih ragu: repositori dibuat **privat**

> Menghapus berkas lalu *commit* ulang **tidak** menghilangkan data dari riwayat Git. > Periksa **sebelum** *commit* pertama.